select ID_ACCOUNT from v_kval_risk_stat
	WHERE 
		KVAL = 1
		AND
		(
			ID_ACCOUNT LIKE '%-MS-%'
			OR ID_ACCOUNT LIKE '%-FX-%'
			OR ID_ACCOUNT LIKE '%-CD-%'
		) 
UNION 
SELECT 'BC21398-MO-03' AS ID_ACCOUNT FROM dual
UNION 
SELECT 'BC21398-MO-05' AS ID_ACCOUNT FROM dual
UNION 
SELECT 'BC21398-MO-06' AS ID_ACCOUNT FROM dual
